// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebaseプロジェクトの設定クラス
/// 注意：このファイルは仮の設定です。実際のFirebaseプロジェクトを作成後、
/// flutterfire configureコマンドで自動生成されたファイルに置き換えてください
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web設定（仮の値）
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-WEB-API-KEY',
    appId: 'YOUR-WEB-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'experiment-cooperation-app',
    authDomain: 'experiment-cooperation-app.firebaseapp.com',
    storageBucket: 'experiment-cooperation-app.appspot.com',
  );

  // Android設定（仮の値）
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-ANDROID-API-KEY',
    appId: 'YOUR-ANDROID-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'experiment-cooperation-app',
    storageBucket: 'experiment-cooperation-app.appspot.com',
  );

  // iOS設定（仮の値）
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY',
    appId: 'YOUR-IOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'experiment-cooperation-app',
    iosBundleId: 'com.example.experimentCooperationApp',
    storageBucket: 'experiment-cooperation-app.appspot.com',
  );

  // macOS設定（仮の値）
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY',
    appId: 'YOUR-MACOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'experiment-cooperation-app',
    iosBundleId: 'com.example.experimentCooperationApp',
    storageBucket: 'experiment-cooperation-app.appspot.com',
  );

  // Windows設定（仮の値）
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-WINDOWS-API-KEY',
    appId: 'YOUR-WINDOWS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'experiment-cooperation-app',
    authDomain: 'experiment-cooperation-app.firebaseapp.com',
    storageBucket: 'experiment-cooperation-app.appspot.com',
  );
}