import 'package:flutter/material.dart';
import '../models/experiment.dart';
import '../services/demo_auth_service.dart';
import '../widgets/home_screen_base.dart';

/// デモ用ホーム画面（Firebase不要）
class HomeScreenDemo extends StatefulWidget {
  final DemoAuthService authService;
  final VoidCallback onLogout;
  
  const HomeScreenDemo({
    super.key,
    required this.authService,
    required this.onLogout,
  });

  @override
  State<HomeScreenDemo> createState() => _HomeScreenDemoState();
}

class _HomeScreenDemoState extends State<HomeScreenDemo> {
  // デモ用の実験データ
  final List<Experiment> _experiments = [
    Experiment(
      id: '1',
      title: '視覚認知実験への参加者募集',
      description: '画面に表示される図形を見て、特定のパターンを見つける実験です。所要時間は約30分です。',
      reward: 1500,
      location: '早稲田大学 戸山キャンパス 33号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_1',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      experimentDate: DateTime.now().add(const Duration(days: 7)),
      endDate: DateTime.now().add(const Duration(days: 14)),
      labName: '認知科学研究室',
      duration: 30,
      maxParticipants: 20,
      requirements: ['視力矯正後1.0以上', '色覚正常'],
    ),
    Experiment(
      id: '2',
      title: 'オンラインアンケート調査',
      description: '大学生の生活習慣に関するアンケート調査です。スマートフォンからも回答可能です。',
      reward: 500,
      location: 'オンライン（Zoomリンクを送付）',
      type: ExperimentType.survey,
      isPaid: true,
      creatorId: 'demo_user_2',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      experimentDate: DateTime.now().add(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 10)),
      labName: '社会心理学研究室',
      duration: 15,
      maxParticipants: 100,
      requirements: ['早稲田大学の学部生'],
    ),
    Experiment(
      id: '3',
      title: '心理学実験の被験者募集（無償）',
      description: '簡単な認知課題を行っていただきます。研究室の卒業論文のデータ収集にご協力ください。',
      reward: 0,
      location: '早稲田大学 西早稲田キャンパス 51号館',
      type: ExperimentType.onsite,
      isPaid: false,
      creatorId: 'demo_user_3',
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      experimentDate: DateTime.now().add(const Duration(days: 5)),
      endDate: DateTime.now().add(const Duration(days: 12)),
      labName: '実験心理学研究室',
      duration: 45,
      maxParticipants: 15,
      requirements: ['日本語ネイティブスピーカー'],
    ),
    Experiment(
      id: '4',
      title: '記憶力測定実験',
      description: '短期記憶と長期記憶の関係を調べる実験です。単語や数字の記憶テストを行います。',
      reward: 2000,
      location: '早稲田大学 戸山キャンパス 34号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_4',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      experimentDate: DateTime.now().add(const Duration(days: 4)),
      endDate: DateTime.now().add(const Duration(days: 11)),
      labName: '認知心理学研究室',
      duration: 45,
      maxParticipants: 15,
      requirements: ['日本語ネイティブスピーカー', '20-30歳'],
    ),
    Experiment(
      id: '5',
      title: 'VR空間での行動観察実験',
      description: 'VRヘッドセットを使用した仮想空間での行動パターンを観察します。',
      reward: 3000,
      location: '早稲田大学 西早稲田キャンパス 63号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_5',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      experimentDate: DateTime.now().add(const Duration(days: 6)),
      endDate: DateTime.now().add(const Duration(days: 20)),
      labName: 'ヒューマンインターフェース研究室',
      duration: 60,
      maxParticipants: 10,
      requirements: ['VR酔いしにくい方', '視力矯正可'],
    ),
    Experiment(
      id: '6',
      title: '音声認識システムの評価実験',
      description: '新しい音声認識システムの精度を評価するため、様々な文章を読み上げていただきます。',
      reward: 1800,
      location: '早稲田大学 西早稲田キャンパス 55号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_6',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      experimentDate: DateTime.now().add(const Duration(days: 2)),
      endDate: DateTime.now().add(const Duration(days: 7)),
      labName: '音響工学研究室',
      duration: 40,
      maxParticipants: 25,
      requirements: ['日本語ネイティブ', '標準語話者'],
    ),
    Experiment(
      id: '7',
      title: 'スマートフォンアプリUIテスト',
      description: '開発中のアプリケーションの使いやすさを評価していただきます。',
      reward: 1000,
      location: 'オンライン（アプリをインストール）',
      type: ExperimentType.online,
      isPaid: true,
      creatorId: 'demo_user_7',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      experimentDate: DateTime.now().add(const Duration(days: 1)),
      endDate: DateTime.now().add(const Duration(days: 5)),
      labName: 'ソフトウェア工学研究室',
      duration: 20,
      maxParticipants: 50,
      requirements: ['iOSまたはAndroidスマートフォン所持'],
    ),
    Experiment(
      id: '8',
      title: '睡眠習慣に関するアンケート',
      description: '大学生の睡眠パターンと学習効率の関係を調査します。',
      reward: 300,
      location: 'オンライン（Googleフォーム）',
      type: ExperimentType.survey,
      isPaid: true,
      creatorId: 'demo_user_8',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      experimentDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 14)),
      labName: '健康科学研究室',
      duration: 10,
      maxParticipants: 200,
      requirements: ['早稲田大学学部生'],
    ),
    Experiment(
      id: '9',
      title: '言語学習アプリの効果測定',
      description: '新しい言語学習方法の効果を測定します。2週間の継続参加が必要です。',
      reward: 5000,
      location: 'オンライン＋戸山キャンパス（事前・事後テスト）',
      type: ExperimentType.online,
      isPaid: true,
      creatorId: 'demo_user_9',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      experimentDate: DateTime.now().add(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 10)),
      labName: '応用言語学研究室',
      duration: 30,
      maxParticipants: 30,
      requirements: ['英語学習意欲がある方', '2週間継続可能な方'],
    ),
    Experiment(
      id: '10',
      title: '運動時の生体反応測定',
      description: 'ウェアラブルデバイスを装着して軽い運動をしていただきます。',
      reward: 2500,
      location: '早稲田大学 戸山キャンパス 体育館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_10',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      experimentDate: DateTime.now().add(const Duration(days: 8)),
      endDate: DateTime.now().add(const Duration(days: 15)),
      labName: 'スポーツ科学研究室',
      duration: 90,
      maxParticipants: 12,
      requirements: ['健康な方', '運動に支障がない方'],
    ),
    Experiment(
      id: '11',
      title: '消費者行動に関する調査',
      description: 'オンラインショッピングの購買行動について質問します。',
      reward: 700,
      location: 'オンライン（Zoom）',
      type: ExperimentType.survey,
      isPaid: true,
      creatorId: 'demo_user_11',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      experimentDate: DateTime.now().add(const Duration(days: 2)),
      endDate: DateTime.now().add(const Duration(days: 9)),
      labName: 'マーケティング研究室',
      duration: 25,
      maxParticipants: 40,
      requirements: ['オンラインショッピング経験あり'],
    ),
    Experiment(
      id: '12',
      title: '顔認識システムの精度検証',
      description: '様々な角度から顔写真を撮影させていただきます。',
      reward: 1200,
      location: '早稲田大学 西早稲田キャンパス 61号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_12',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      experimentDate: DateTime.now().add(const Duration(days: 5)),
      endDate: DateTime.now().add(const Duration(days: 12)),
      labName: '画像処理研究室',
      duration: 35,
      maxParticipants: 18,
      requirements: ['顔写真撮影に同意できる方'],
    ),
    Experiment(
      id: '13',
      title: '集中力測定実験（無償）',
      description: '様々な環境下での集中力の変化を測定します。',
      reward: 0,
      location: '早稲田大学 戸山キャンパス 36号館',
      type: ExperimentType.onsite,
      isPaid: false,
      creatorId: 'demo_user_13',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      experimentDate: DateTime.now().add(const Duration(days: 4)),
      endDate: DateTime.now().add(const Duration(days: 11)),
      labName: '教育心理学研究室',
      duration: 50,
      maxParticipants: 20,
      requirements: ['学部生・大学院生'],
    ),
    Experiment(
      id: '14',
      title: 'ゲームプレイ中の脳活動測定',
      description: '脳波計を装着してゲームをプレイしていただきます。',
      reward: 3500,
      location: '早稲田大学 西早稲田キャンパス 52号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_14',
      createdAt: DateTime.now().subtract(const Duration(hours: 18)),
      experimentDate: DateTime.now().add(const Duration(days: 7)),
      endDate: DateTime.now().add(const Duration(days: 21)),
      labName: '神経科学研究室',
      duration: 120,
      maxParticipants: 8,
      requirements: ['ゲーム経験者', '脳波測定に同意'],
    ),
    Experiment(
      id: '15',
      title: '食習慣調査アンケート',
      description: '大学生の食生活について調査します。1週間の食事記録をお願いします。',
      reward: 1500,
      location: 'オンライン（専用アプリ）',
      type: ExperimentType.survey,
      isPaid: true,
      creatorId: 'demo_user_15',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      experimentDate: DateTime.now().add(const Duration(days: 1)),
      endDate: DateTime.now().add(const Duration(days: 8)),
      labName: '栄養学研究室',
      duration: 15,
      maxParticipants: 60,
      requirements: ['1週間継続記録可能な方'],
    ),
    Experiment(
      id: '16',
      title: '歩行動作分析実験',
      description: 'モーションキャプチャを使用して歩行パターンを分析します。',
      reward: 2200,
      location: '早稲田大学 所沢キャンパス',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_16',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      experimentDate: DateTime.now().add(const Duration(days: 9)),
      endDate: DateTime.now().add(const Duration(days: 16)),
      labName: 'バイオメカニクス研究室',
      duration: 75,
      maxParticipants: 14,
      requirements: ['健康な方', '運動着持参'],
    ),
    Experiment(
      id: '17',
      title: 'プログラミング学習支援システムの評価',
      description: '新しいプログラミング学習ツールを使用していただき、フィードバックをお願いします。',
      reward: 800,
      location: 'オンライン',
      type: ExperimentType.online,
      isPaid: true,
      creatorId: 'demo_user_17',
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      experimentDate: DateTime.now().add(const Duration(days: 2)),
      endDate: DateTime.now().add(const Duration(days: 7)),
      labName: '情報教育研究室',
      duration: 30,
      maxParticipants: 35,
      requirements: ['プログラミング初心者'],
    ),
    Experiment(
      id: '18',
      title: '環境音が作業効率に与える影響',
      description: '様々な環境音の中で簡単な作業をしていただきます。',
      reward: 1600,
      location: '早稲田大学 戸山キャンパス 32号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_18',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      experimentDate: DateTime.now().add(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 10)),
      labName: '環境心理学研究室',
      duration: 55,
      maxParticipants: 22,
      requirements: ['聴力正常な方'],
    ),
    Experiment(
      id: '19',
      title: '対話型AIの評価実験',
      description: 'チャットボットと会話していただき、自然さを評価します。',
      reward: 900,
      location: 'オンライン',
      type: ExperimentType.online,
      isPaid: true,
      creatorId: 'demo_user_19',
      createdAt: DateTime.now().subtract(const Duration(hours: 15)),
      experimentDate: DateTime.now().add(const Duration(days: 1)),
      endDate: DateTime.now().add(const Duration(days: 4)),
      labName: '自然言語処理研究室',
      duration: 25,
      maxParticipants: 45,
      requirements: ['日本語ネイティブ'],
    ),
    Experiment(
      id: '20',
      title: '色彩感覚テスト（無償）',
      description: '色の識別能力と感性を測定する実験です。',
      reward: 0,
      location: '早稲田大学 戸山キャンパス 39号館',
      type: ExperimentType.onsite,
      isPaid: false,
      creatorId: 'demo_user_20',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      experimentDate: DateTime.now().add(const Duration(days: 6)),
      endDate: DateTime.now().add(const Duration(days: 13)),
      labName: '視覚デザイン研究室',
      duration: 40,
      maxParticipants: 25,
      requirements: ['色覚正常な方'],
    ),
    Experiment(
      id: '21',
      title: '瞑想アプリの効果検証',
      description: '瞑想アプリを1週間使用していただき、ストレス軽減効果を測定します。',
      reward: 2000,
      location: 'オンライン＋事前事後測定（戸山）',
      type: ExperimentType.online,
      isPaid: true,
      creatorId: 'demo_user_21',
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      experimentDate: DateTime.now().add(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 17)),
      labName: '臨床心理学研究室',
      duration: 20,
      maxParticipants: 30,
      requirements: ['継続参加可能な方', 'スマートフォン所持'],
    ),
    Experiment(
      id: '22',
      title: 'SNS利用と幸福度の関係調査',
      description: 'SNSの利用状況と主観的幸福度についてインタビューします。',
      reward: 1100,
      location: 'オンライン（Zoom）',
      type: ExperimentType.survey,
      isPaid: true,
      creatorId: 'demo_user_22',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      experimentDate: DateTime.now().add(const Duration(days: 2)),
      endDate: DateTime.now().add(const Duration(days: 8)),
      labName: '社会情報学研究室',
      duration: 45,
      maxParticipants: 24,
      requirements: ['SNS利用者', '18-25歳'],
    ),
    Experiment(
      id: '23',
      title: '筋電図測定実験',
      description: '簡単な動作中の筋肉の活動を測定します。',
      reward: 2800,
      location: '早稲田大学 所沢キャンパス',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_23',
      createdAt: DateTime.now().subtract(const Duration(hours: 20)),
      experimentDate: DateTime.now().add(const Duration(days: 10)),
      endDate: DateTime.now().add(const Duration(days: 24)),
      labName: '運動生理学研究室',
      duration: 100,
      maxParticipants: 10,
      requirements: ['健康な方', '運動制限なし'],
    ),
    Experiment(
      id: '24',
      title: 'AR技術を用いた学習効果の検証',
      description: 'AR教材を使った学習と従来の学習方法を比較します。',
      reward: 1700,
      location: '早稲田大学 西早稲田キャンパス 60号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_24',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      experimentDate: DateTime.now().add(const Duration(days: 5)),
      endDate: DateTime.now().add(const Duration(days: 19)),
      labName: '教育工学研究室',
      duration: 65,
      maxParticipants: 16,
      requirements: ['ARデバイス使用経験不問'],
    ),
    Experiment(
      id: '25',
      title: 'オンライン授業の満足度調査',
      description: 'オンライン授業に関する経験と改善点についてお聞きします。',
      reward: 400,
      location: 'オンライン（アンケート）',
      type: ExperimentType.survey,
      isPaid: true,
      creatorId: 'demo_user_25',
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
      experimentDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 6)),
      labName: '高等教育研究室',
      duration: 15,
      maxParticipants: 150,
      requirements: ['オンライン授業経験者'],
    ),
    Experiment(
      id: '26',
      title: '表情認識システムの開発協力（無償）',
      description: '様々な表情を撮影させていただき、データベース作成に協力していただきます。',
      reward: 0,
      location: '早稲田大学 西早稲田キャンパス 57号館',
      type: ExperimentType.onsite,
      isPaid: false,
      creatorId: 'demo_user_26',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      experimentDate: DateTime.now().add(const Duration(days: 4)),
      endDate: DateTime.now().add(const Duration(days: 11)),
      labName: '感情認識研究室',
      duration: 30,
      maxParticipants: 40,
      requirements: ['顔撮影に同意'],
    ),
    Experiment(
      id: '27',
      title: '音楽が勉強効率に与える影響',
      description: '様々なジャンルの音楽を聴きながら課題に取り組んでいただきます。',
      reward: 1400,
      location: '早稲田大学 戸山キャンパス 38号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_27',
      createdAt: DateTime.now().subtract(const Duration(hours: 7)),
      experimentDate: DateTime.now().add(const Duration(days: 3)),
      endDate: DateTime.now().add(const Duration(days: 9)),
      labName: '音楽心理学研究室',
      duration: 70,
      maxParticipants: 28,
      requirements: ['聴力正常', '音楽好き歓迎'],
    ),
    Experiment(
      id: '28',
      title: '新型コントローラーの操作性評価',
      description: '開発中のゲームコントローラーを使用していただき、操作感をフィードバックしていただきます。',
      reward: 1900,
      location: '早稲田大学 西早稲田キャンパス 56号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_28',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      experimentDate: DateTime.now().add(const Duration(days: 6)),
      endDate: DateTime.now().add(const Duration(days: 15)),
      labName: 'インタラクションデザイン研究室',
      duration: 80,
      maxParticipants: 12,
      requirements: ['ゲーム経験あり'],
    ),
    Experiment(
      id: '29',
      title: '外国語学習モチベーション調査',
      description: '外国語学習に対する動機づけについてインタビューします。',
      reward: 600,
      location: 'オンライン（Google Meet）',
      type: ExperimentType.survey,
      isPaid: true,
      creatorId: 'demo_user_29',
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      experimentDate: DateTime.now().add(const Duration(days: 1)),
      endDate: DateTime.now().add(const Duration(days: 7)),
      labName: '言語教育研究室',
      duration: 30,
      maxParticipants: 50,
      requirements: ['外国語学習経験者'],
    ),
    Experiment(
      id: '30',
      title: '視線追跡を用いた読書行動分析',
      description: 'アイトラッカーを使用して読書中の視線の動きを記録します。',
      reward: 2300,
      location: '早稲田大学 戸山キャンパス 31号館',
      type: ExperimentType.onsite,
      isPaid: true,
      creatorId: 'demo_user_30',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      experimentDate: DateTime.now().add(const Duration(days: 5)),
      endDate: DateTime.now().add(const Duration(days: 14)),
      labName: '読書科学研究室',
      duration: 60,
      maxParticipants: 16,
      requirements: ['日本語読解能力', '眼鏡・コンタクト可'],
    ),
  ];

  void _handleCreateExperiment() {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('デモモードでは実験作成機能は利用できません'),
        backgroundColor: Colors.orange,
        duration: Duration(seconds: 3),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return HomeScreenBase(
      title: 'わせラボ',
      experiments: _experiments,
      canCreateExperiment: widget.authService.canCreateExperiment,
      userName: widget.authService.currentUserName,
      isWasedaUser: widget.authService.isWasedaUser,
      onLogout: widget.onLogout,
      onCreateExperiment: widget.authService.canCreateExperiment 
          ? _handleCreateExperiment 
          : null,
    );
  }
}